name: Epic Tasks Template
description: 지라 에픽과 연동될 이슈 템플릿
title: "[EPIC-KEY] 제목"
body:
  - type: markdown
    attributes:
      value: |
        ## 에픽 설명
        이 이슈는 지라 에픽과 연동됩니다. 아래 체크리스트에 추가되는 작업들은 자동으로 지라의 하위 작업으로 생성됩니다.

  - type: textarea
    id: description
    attributes:
      label: 설명
      description: 이 에픽에 대한 간략한 설명을 입력하세요.
      placeholder: 이 기능은...

  - type: checkboxes
    id: tasks
    attributes:
      label: 하위 작업
      description: 체크된 항목들은 에픽의 하위 작업으로 생성됩니다.
      options:
        - label: 설계
          required: false
        - label: UI 구현
          required: false
        - label: DB 연동
          required: false
        - label: 애니메이션 추가
          required: false

  - type: textarea
    id: additional_tasks
    attributes:
      label: 추가 하위 작업
      description: 위에 나열되지 않은 추가 하위 작업을 체크리스트 형식으로 입력하세요 (예: - [ ] 작업명)
      placeholder: |
        - [ ] 추가 작업 1
        - [ ] 추가 작업 2
