name: Close Issue and Update Jira Ticket
on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  close-issue-update-jira:
    name: Close GitHub Issue and Update Jira Ticket
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      
      - name: Extract issue number from PR
        id: extract-info
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          
          # PR 제목에서 Jira 키 추출 (예: [FCC-123] 제목)
          JIRA_KEY_FROM_TITLE=$(echo "$PR_TITLE" | grep -oE '\[[A-Z]+-[0-9]+\]' | tr -d '[]' || echo "")
          
          # 브랜치 이름에서 Jira 키 추출 (예: FCC-123-branch-name)
          JIRA_KEY_FROM_BRANCH=$(echo "$BRANCH_NAME" | grep -oE '^[A-Z]+-[0-9]+' || echo "")
          
          # PR 본문에서 이슈 번호 추출 (예: close #123)
          ISSUE_NUMBER=$(echo "$PR_BODY" | grep -oE '(close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)\s+#([0-9]+)' | grep -oE '[0-9]+' || echo "")
          
          # 이슈 번호가 없으면 브랜치 이름에서 추출 (예: 123-branch-name)
          if [ -z "$ISSUE_NUMBER" ]; then
            ISSUE_NUMBER=$(echo "$BRANCH_NAME" | grep -oE '^[0-9]+' || echo "")
          fi
          
          # 최종 Jira 키 결정
          JIRA_KEY="$JIRA_KEY_FROM_TITLE"
          if [ -z "$JIRA_KEY" ]; then
            JIRA_KEY="$JIRA_KEY_FROM_BRANCH"
          fi
          
          echo "jira_key=$JIRA_KEY" >> $GITHUB_OUTPUT
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
          
          echo "Extracted Jira Key: $JIRA_KEY"
          echo "Extracted Issue Number: $ISSUE_NUMBER"
      
      - name: Close GitHub Issue
        if: steps.extract-info.outputs.issue_number != ''
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.extract-info.outputs.issue_number }}
      
      - name: Add comment to GitHub Issue
        if: steps.extract-info.outputs.issue_number != '' && steps.extract-info.outputs.jira_key != ''
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.extract-info.outputs.issue_number }}
          body: |
            이 이슈는 PR #${{ github.event.pull_request.number }}가 병합되어 닫혔습니다.
            관련 Jira 티켓 [${{ steps.extract-info.outputs.jira_key }}](${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.extract-info.outputs.jira_key }})도 완료 처리되었습니다.
      
      - name: Transition Jira Issue to Done
        if: steps.extract-info.outputs.jira_key != ''
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.extract-info.outputs.jira_key }}
          transition: "Done"
      
      - name: Add comment to Jira Issue
        if: steps.extract-info.outputs.jira_key != ''
        uses: atlassian/gajira-comment@v3
        with:
          issue: ${{ steps.extract-info.outputs.jira_key }}
          comment: |
            GitHub PR #${{ github.event.pull_request.number }} ([${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }}))가 병합되었습니다.
            관련 GitHub 이슈도 자동으로 닫혔습니다.
